image: acfr/ros-build:melodic
variables:
  ROS_DISTRO: "melodic"
  UBUNTU_DISTRO: "bionic"
  CI_SOURCE_PATH: "$CI_PROJECT_DIR"
  ROS_PARALLEL_JOBS: "-j8 -l6"
  GIT_DEPTH: "3"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_SSL_NO_VERIFY: "true"

stages:
  - build
    #- test
    #- deb
  - deploy

build:
  stage: build
  script:
    - wget http://acfr-ros-pro-1.srv.sydney.edu.au:4440/build-ros-deb.sh
    - chmod +x ./build-ros-deb.sh
    - ./build-ros-deb.sh
  artifacts:
    paths:
      - debs

deploy:
  only:
    - melodic
  stage: deploy
  dependencies:
    - build
  script:
    - cd debs
    - if [ $CI_PROJECT_NAMESPACE == 'zio' ];
        then find . -name '*.deb' -print0 | xargs -0 -n1 basename | while read DEB;
        do dpkg-deb -I "$DEB" ;
        curl -f -X POST -F file=@"$DEB" "http://aptly-submit:${APTLY_PASSWORD}@acfr-ros-pro-1.srv.sydney.edu.au:4441/api/files/incoming_pkgs_${ROS_DISTRO}" ;
        curl -f -X POST "http://aptly-submit:${APTLY_PASSWORD}@acfr-ros-pro-1.srv.sydney.edu.au:4441/api/repos/zio-${ROS_DISTRO}/file/incoming_pkgs_${ROS_DISTRO}" ;
        curl -f -X PUT "http://aptly-submit:${APTLY_PASSWORD}@acfr-ros-pro-1.srv.sydney.edu.au:4441/api/publish/zio-${ROS_DISTRO}/${UBUNTU_DISTRO}" ;
        done ;
        fi
